services:

  postgres:
    image: postgres:17
    container_name: api-gateway-postgres
    environment:
      POSTGRES_DB: gateway_platform
      POSTGRES_USER: gateway
      POSTGRES_PASSWORD: gateway
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: