spring:
  config:
    import: optional:classpath:application-local.properties

  application:
    name: requests-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/api-gateway-platform}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8080/realms/api-gateway-platform/protocol/openid-connect/certs}

server:
  port: 8085
  servlet:
    context-path: /requests-management