spring:
  config:
    import: optional:classpath:application-local.properties

  application:
    name: model

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8083
  servlet:
    context-path: /model-management
