spring:
  # Configuración general de la aplicación Spring Boot
  application:
    name: proxy

  cloud:
    gateway:
      server:
        webflux:
          # Lista de rutas que va a gestionar el Gateway
          routes:
            # Identificador único de esta ruta
            - id: products
              # API real a la que vamos a redirigir las peticiones
              uri: http://localhost:8081
              # Condiciones que debe cumplir una petición
              # para que utilice esta ruta
              predicates:
                # Cualquier petición que empiece por /todos/
                # será enviada a la API configurada arriba
                #
                # Ejemplo:
                # localhost:9000/todos/1
                #          ?
                # https://jsonplaceholder.typicode.com/todos/1
                - Path=/products/**
            - id: users
              uri: http://localhost:8082
              predicates:
                - Path=/users/**


# Puerto donde estará escuchando nuestro Gateway
server:
  port: 9000