spring:
  application:
    name: proxy

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/api-gateway-platform}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8080/realms/api-gateway-platform/protocol/openid-connect/certs}

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: api-management
              uri: ${PRODUCTS_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api-management/**

            - id: users-management
              uri: ${USERS_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/users-management/**

            - id: protected-api-management
              uri: ${PROTECTED_SERVICE_URL:http://localhost:8084}
              predicates:
                - Path=/api-protected-management/**
              filters:
                - name: RequestLogging
                  args:
                    apiCode: apis-management
                - ApiKeyAuthentication
                - name: ApiPermission
                  args:
                    apiCode: apis-management
                - RateLimit

            - id: requests-management
              uri: ${REQUESTS_SERVICE_URL:http://localhost:8085}
              predicates:
                - Path=/requests-management/request-logs,/requests-management/request-logs/**

server:
  port: 9000

services:
  users:
    url: ${USERS_SERVICE_URL:http://localhost:8082}
  requests:
    url: ${REQUESTS_SERVICE_URL:http://localhost:8085}