spring:
  application:
    name: proxy

  cloud:
    gateway:
      server:
        webflux:
          routes:

            # Administración: NO API Key
            - id: api-management
              uri: http://localhost:8081
              predicates:
                - Path=/api-management/**

            # Administración: NO API Key
            - id: users-management
              uri: http://localhost:8082
              predicates:
                - Path=/users-management/**

            # API externa: SÍ API Key
            - id: protected-api-management
              uri: http://localhost:8084
              predicates:
                - Path=/api-protected-management/**
              filters:
                - ApiKeyAuthentication

            # Administración: NO API Key
            - id: model-management
              uri: http://localhost:8083
              predicates:
                - Path=/model-management/api/model/**

server:
  port: 9000